[package]
name = "move"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosStdlib = { local = "../../framework/aptos-stdlib" }

[addresses]
future = "_"
admin_addr = "46c296bd3c1eb6c8b858cc459ed7d6a3d4e664216683b834a9381c176d87c369"
